const fs = require('fs');
let lines = fs.readFileSync('scripts/lib/market_research.js', 'utf8').split(/\r?\n/);

let start = lines.findIndex(l => l.includes('const KAKAKU_CATEGORY_MAP = {'));
let end = -1;
for (let i = start + 1; i < lines.length; i++) {
    if (lines[i] === '};') {
        end = i;
        break;
    }
}

if (start !== -1 && end !== -1) {
    const cleanMap = [
        "const KAKAKU_CATEGORY_MAP = {",
        "    '完全ワイヤレス': { path: 'headphones', code: '2046' },",
        "    'ワイヤレスイヤホン': { path: 'headphones', code: '2046' },",
        "    'イヤホン': { path: 'headphones', code: '2046' },",
        "    'ヘッドホン': { path: 'headphones', code: '2046' },",
        "    'Bluetooth': { path: 'headphones', code: '2046' },",
        "    'カナル': { path: 'headphones', code: '2046' },",
        "    '骨伝導': { path: 'headphones', code: '2046' },",
        "    'ヘッドセット': { path: 'headset', code: '2049' },",
        "    'スピーカー': { path: 'speaker', code: '2047' },",
        "    'Bluetoothスピーカー': { path: 'bluetooth-speaker', code: '7091' },",
        "    'サウンドバー': { path: 'sound-bar', code: '7073' },",
        "    'ホームシアター': { path: 'home-theater-speaker', code: '2048' },",
        "    'AVアンプ': { path: 'av-amp', code: '2056' },",
        "    'プリメインアンプ': { path: 'pre-main-amp', code: '2059' },",
        "    'ミニコンポ': { path: 'mini-component', code: '2054' },",
        "    'ポータブルオーディオ': { path: 'digital-audio-player', code: '2053' },",
        "    'DAP': { path: 'digital-audio-player', code: '2053' },",
        "    'ヘッドホンアンプ': { path: 'headphone-amp', code: '7020' },",
        "    'テレビ': { path: 'lcd-tv', code: '2041' },",
        "    '液晶テレビ': { path: 'lcd-tv', code: '2041' },",
        "    '有機EL': { path: 'lcd-tv', code: '2041' },",
        "    'ブルーレイレコーダー': { path: 'dvd-recorder', code: '2022' },",
        "    'DVDレコーダー': { path: 'dvd-recorder', code: '2022' },",
        "    'ブルーレイプレーヤー': { path: 'dvd-player', code: '2025' },",
        "    'プロジェクタ': { path: 'projector', code: '2024' },",
        "    'チューナー': { path: 'dtv-tuner', code: '2071' },",
        "    '冷蔵庫': { path: 'freezer', code: '2115' },",
        "    '冷凍庫': { path: 'freezer', code: '2116' },",
        "    'ワインセラー': { path: 'wine-cellar', code: '2119' },",
        "    '炊飯器': { path: 'rice-cooker', code: '2125' },",
        "    'IH炊飯器': { path: 'rice-cooker', code: '2125' },",
        "    '電子レンジ': { path: 'microwave-oven', code: '2117' },",
        "    'オーブンレンジ': { path: 'microwave-oven', code: '2117' },",
        "    'トースター': { path: 'toaster', code: '2118' },",
        "    'ホームベーカリー': { path: 'homebakery', code: '2119' },",
        "    'ミキサー': { path: 'mixer', code: '2122' },",
        "    'フードプロセッサー': { path: 'mixer', code: '2122' },",
        "    '電気ポット': { path: 'electric-pot', code: '2120' },",
        "    '電気ケトル': { path: 'electric-pot', code: '2120' },",
        "    'コーヒーメーカー': { path: 'coffee-maker', code: '2121' },",
        "    'エスプレッソマシン': { path: 'espresso-machine', code: '7019' },",
        "    '食器洗い機': { path: 'dish-washer', code: '2124' },",
        "    '食洗機': { path: 'dish-washer', code: '2124' },",
        "    'IHクッキングヒーター': { path: 'ihcooking-heater', code: '2134' },",
        "    'ホットプレート': { path: 'hot-plate', code: '2131' },",
        "    '圧力鍋': { path: 'pressure-cooker', code: '7074' },",
        "    '電気圧力鍋': { path: 'electric-pressure-cooker', code: '7091' },",
        "    '低温調理器': { path: 'low-temperature-cooker', code: '7092' },",
        "    'ノンフライヤー': { path: 'non-fryer', code: '7058' },",
        "    '掃除機': { path: 'vacuum', code: '2165' },",
        "    'コードレス掃除機': { path: 'cordless-vacuum', code: '7084' },",
        "    'ロボット掃除機': { path: 'robot-vacuum', code: '7032' },",
        "    'ハンディ掃除機': { path: 'handy-vacuum', code: '2167' },",
        "    '布団クリーナー': { path: 'futon-cleaner', code: '7057' },",
        "    'スチームクリーナー': { path: 'steam-cleaner', code: '7044' },",
        "    '高圧洗浄機': { path: 'pressure-washer', code: '7027' },",
        "    '洗濯機': { path: 'washing-machine', code: '2107' },",
        "    'ドラム式洗濯機': { path: 'washing-machine', code: '2107' },",
        "    '縦型洗濯機': { path: 'washing-machine', code: '2107' },",
        "    '衣類乾燥機': { path: 'clothes-dryer', code: '2109' },",
        "    '布団乾燥機': { path: 'futon-dryer', code: '2186' },",
        "    'アイロン': { path: 'iron', code: '2183' },",
        "    'ミシン': { path: 'sewing-machine', code: '2163' },",
        "    'エアコン': { path: 'aircon', code: '2180' },",
        "    'クーラー': { path: 'aircon', code: '2180' },",
        "    '空気清浄機': { path: 'air-purifier', code: '2147' },",
        "    '除湿機': { path: 'dehumidifier', code: '2175' },",
        "    '加湿器': { path: 'humidifier', code: '2161' },",
        "    '扇風機': { path: 'fan', code: '2174' },",
        "    'サーキュレーター': { path: 'circulator', code: '7042' },",
        "    'ヒーター': { path: 'heater', code: '2150' },",
        "    'ストーブ': { path: 'heater', code: '2150' },",
        "    'ファンヒーター': { path: 'fan-heater', code: '2151' },",
        "    'ホットカーペット': { path: 'hot-carpet', code: '2156' },",
        "    'こたつ': { path: 'kotatsu', code: '2158' },",
        "    '電気毛布': { path: 'electric-blanket', code: '2159' },",
        "    'シェーバー': { path: 'shaver', code: '2143' },",
        "    '電気シェーバー': { path: 'shaver', code: '2143' },",
        "    '脱毛器': { path: 'epilator', code: '2144' },",
        "    'バリカン': { path: 'hair-clipper', code: '2145' },",
        "    '電動歯ブラシ': { path: 'electric-toothbrush', code: '2149' },",
        "    'ヘアドライヤー': { path: 'hair-dryer', code: '2187' },",
        "    'ドライヤー': { path: 'hair-dryer', code: '2187' },",
        "    'ヘアアイロン': { path: 'hair-iron', code: '7028' },",
        "    '美顔器': { path: 'facial-equipment', code: '7047' },",
        "    'マッサージ器': { path: 'massager', code: '2191' },",
        "    'マッサージチェア': { path: 'massage-chair', code: '2192' },",
        "    '体重計': { path: 'weight-scale', code: '2148' },",
        "    '体脂肪計': { path: 'weight-scale', code: '2148' },",
        "    '体組成計': { path: 'weight-scale', code: '2148' },",
        "    '血圧計': { path: 'blood-pressure-monitor', code: '2193' },",
        "    '体温計': { path: 'thermometer', code: '7048' },",
        "    '電子辞書': { path: 'electronic-dictionary', code: '2073' },",
        "    '電話機': { path: 'phone', code: '2185' },",
        "    'FAX': { path: 'fax', code: '2198' },",
        "    'ラジオ': { path: 'radio', code: '2055' },",
        "    'モバイルバッテリー': { path: 'portable-charger', code: '7062' },",
        "    'ポータブル電源': { path: 'portable-power', code: '7089' },",
        "    '充電器': { path: 'charger', code: '7063' },",
        "    'シーリングライト': { path: 'ceiling-light', code: '2081' },",
        "    'LEDシーリングライト': { path: 'led-ceiling-light', code: '7031' },",
        "    'LED電球': { path: 'led-light', code: '7030' },",
        "    'デスクライト': { path: 'desk-light', code: '2082' },",
        "    'スタンドライト': { path: 'stand-light', code: '2084' },",
        "    '無線LANルーター': { path: 'wifi-router', code: '2077' },",
        "    'Wi-Fiルーター': { path: 'wifi-router', code: '2077' },",
        "    'ルーター': { path: 'wifi-router', code: '2077' },",
        "    '浄水器': { path: 'water-purifier', code: '2137' },",
        "    'ウォーターサーバー': { path: 'water-server', code: '7060' },",
        "    '温水洗浄便座': { path: 'washlet', code: '2136' },",
        "    'ウォシュレット': { path: 'washlet', code: '2136' },",
        "    'ガスコンロ': { path: 'gas-stove', code: '2133' },",
        "    '給湯器': { path: 'water-heater', code: '2135' },",
        "    'インターホン': { path: 'intercom', code: '2197' },",
        "    '防犯カメラ': { path: 'network-camera', code: '7035' },",
        "    'ネットワークカメラ': { path: 'network-camera', code: '7035' },",
        "    'デジタルカメラ': { section: 'camera', path: 'digital-camera', code: '0050' },",
        "    'デジカメ': { section: 'camera', path: 'digital-camera', code: '0050' },",
        "    'ミラーレス': { section: 'camera', path: 'mirrorless', code: '0049' },",
        "    '一眼レフ': { section: 'camera', path: 'digital-slr', code: '0049' },",
        "    'ビデオカメラ': { section: 'camera', path: 'video-camera', code: '0060' },",
        "    'アクションカメラ': { section: 'camera', path: 'action-camera', code: '7064' },",
        "    'レンズ': { section: 'camera', path: 'camera-lens', code: '1050' },",
        "    '三脚': { section: 'camera', path: 'tripod', code: '1033' },",
        "    'ノートパソコン': { section: 'pc', path: 'note-pc', code: '0020' },",
        "    'ノートPC': { section: 'pc', path: 'note-pc', code: '0020' },",
        "    'デスクトップPC': { section: 'pc', path: 'desktop-pc', code: '0010' },",
        "    'タブレット': { section: 'pc', path: 'tablet', code: '0030' },",
        "    'iPad': { section: 'pc', path: 'tablet', code: '0030' },",
        "    'プリンタ': { section: 'pc', path: 'printer', code: '0060' },",
        "    'モニター': { section: 'pc', path: 'lcd-monitor', code: '0085' },",
        "    'ディスプレイ': { section: 'pc', path: 'lcd-monitor', code: '0085' },",
        "    'キーボード': { section: 'pc', path: 'keyboard', code: '0150' },",
        "    'マウス': { section: 'pc', path: 'mouse', code: '0160' },",
        "    'SSD': { section: 'pc', path: 'ssd', code: '0537' },",
        "    'HDD': { section: 'pc', path: 'hdd-35inch', code: '0530' },",
        "    '外付けHDD': { section: 'pc', path: 'external-hdd', code: '0538' },",
        "    'USBメモリ': { section: 'pc', path: 'usb-memory', code: '0536' },",
        "    'SDカード': { section: 'pc', path: 'sd-card', code: '0528' },",
        "    'カーナビ': { section: 'car_goods', path: 'car-navigation', code: '2010' },",
        "    'ドライブレコーダー': { section: 'car_goods', path: 'drive-recorder', code: '7034' },",
        "    'ドラレコ': { section: 'car_goods', path: 'drive-recorder', code: '7034' },",
        "    'レーダー探知機': { section: 'car_goods', path: 'car-radar', code: '2005' },",
        "    'カーオーディオ': { section: 'car_goods', path: 'car-audio', code: '2015' },",
        "    'タイヤ': { section: 'car_goods', path: 'tire', code: '7050' },",
        "    'ゲーム機': { path: 'game-machine', code: '2501' },",
        "    'PlayStation': { path: 'game-machine', code: '2501' },",
        "    'Nintendo': { path: 'game-machine', code: '2501' },",
        "    'Switch': { path: 'game-machine', code: '2501' },",
        "    'PS5': { path: 'game-machine', code: '2501' },",
        "    'Xbox': { path: 'game-machine', code: '2501' },",
        "    'フィギュア': { section: 'hobby', path: 'figure', code: '3010' },",
        "    'プラモデル': { section: 'hobby', path: 'plastic-model', code: '3015' },",
        "    'ラジコン': { section: 'hobby', path: 'radio-control', code: '3020' },",
        "    'ミニ四駆': { section: 'hobby', path: 'mini-yonku', code: '3025' },",
        "    'ドローン': { section: 'hobby', path: 'drone', code: '7065' },",
        "    '電子ピアノ': { section: 'hobby', path: 'electronic-piano', code: '2570' },",
        "    'キーボード楽器': { section: 'hobby', path: 'keyboard-instrument', code: '2571' },",
        "    'ギター': { section: 'hobby', path: 'guitar', code: '2575' },",
        "    '電子楽器': { section: 'hobby', path: 'electronic-instrument', code: '2573' },",
        "    'スマートフォン': { section: 'keitai', path: 'smartphone', code: '7041' },",
        "    'スマホ': { section: 'keitai', path: 'smartphone', code: '7041' },",
        "    'iPhone': { section: 'keitai', path: 'smartphone', code: '7041' },",
        "    'Android': { section: 'keitai', path: 'smartphone', code: '7041' },",
        "    '携帯電話': { section: 'keitai', path: 'phs', code: '3147' },",
        "    'スマートウォッチ': { section: 'keitai', path: 'smartwatch', code: '7066' },",
        "    'ソファ': { section: 'interior', path: 'sofa', code: '0066' },",
        "    'ソファー': { section: 'interior', path: 'sofa', code: '0066' },",
        "    'ベッド': { section: 'interior', path: 'bed', code: '0062' },",
        "    'マットレス': { section: 'interior', path: 'mattress', code: '0063' },",
        "    'デスク': { section: 'interior', path: 'desk', code: '0010' },",
        "    '机': { section: 'interior', path: 'desk', code: '0010' },",
        "    'チェア': { section: 'interior', path: 'chair', code: '0020' },",
        "    '椅子': { section: 'interior', path: 'chair', code: '0020' },",
        "    'オフィスチェア': { section: 'interior', path: 'office-chair', code: '0021' },",
        "    'ゲーミングチェア': { section: 'interior', path: 'gaming-chair', code: '7090' },",
        "    'テーブル': { section: 'interior', path: 'table', code: '0030' },",
        "    'ダイニングテーブル': { section: 'interior', path: 'dining-table', code: '0031' },",
        "    '本棚': { section: 'interior', path: 'bookshelf', code: '0050' },",
        "    'ラック': { section: 'interior', path: 'rack', code: '0051' },",
        "    '収納': { section: 'interior', path: 'storage', code: '0052' },",
        "    'カーテン': { section: 'interior', path: 'curtain', code: '0070' },",
        "    'ブラインド': { section: 'interior', path: 'blind', code: '0071' },",
        "    'カーペット': { section: 'interior', path: 'carpet', code: '0080' },",
        "    'ラグ': { section: 'interior', path: 'rug', code: '0081' },",
        "    'クッション': { section: 'interior', path: 'cushion', code: '0090' },",
        "    '枕': { section: 'interior', path: 'pillow', code: '0064' },",
        "    '布団': { section: 'interior', path: 'futon', code: '0065' },",
        "    'バッグ': { section: 'fashion', path: 'bag', code: '0010' },",
        "    'リュック': { section: 'fashion', path: 'backpack', code: '0011' },",
        "    'バックパック': { section: 'fashion', path: 'backpack', code: '0011' },",
        "    'トートバッグ': { section: 'fashion', path: 'tote-bag', code: '0012' },",
        "    'ショルダーバッグ': { section: 'fashion', path: 'shoulder-bag', code: '0013' },",
        "    '財布': { section: 'fashion', path: 'wallet', code: '0020' },",
        "    'サングラス': { section: 'fashion', path: 'sunglasses', code: '0030' },",
        "    'メガネ': { section: 'fashion', path: 'glasses', code: '0031' },",
        "    'ベルト': { section: 'fashion', path: 'belt', code: '0040' },",
        "    'ネクタイ': { section: 'fashion', path: 'necktie', code: '0041' },",
        "    'マフラー': { section: 'fashion', path: 'muffler', code: '0050' },",
        "    'ストール': { section: 'fashion', path: 'stole', code: '0051' },",
        "    '帽子': { section: 'fashion', path: 'hat', code: '0060' },",
        "    'キャップ': { section: 'fashion', path: 'cap', code: '0061' },",
        "    '手袋': { section: 'fashion', path: 'gloves', code: '0070' },",
        "    '傘': { section: 'fashion', path: 'umbrella', code: '0080' },",
        "    'レインウェア': { section: 'fashion', path: 'rainwear', code: '0081' },",
        "    'スニーカー': { section: 'shoes', path: 'sneakers', code: '0010' },",
        "    'ランニングシューズ': { section: 'shoes', path: 'running-shoes', code: '0011' },",
        "    'ビジネスシューズ': { section: 'shoes', path: 'business-shoes', code: '0020' },",
        "    '革靴': { section: 'shoes', path: 'leather-shoes', code: '0021' },",
        "    'ブーツ': { section: 'shoes', path: 'boots', code: '0030' },",
        "    'サンダル': { section: 'shoes', path: 'sandals', code: '0040' },",
        "    'スリッパ': { section: 'shoes', path: 'slippers', code: '0050' },",
        "    '腕時計': { section: 'watch_accessory', path: 'watch', code: '0010' },",
        "    'メンズ腕時計': { section: 'watch_accessory', path: 'mens-watch', code: '0011' },",
        "    'レディース腕時計': { section: 'watch_accessory', path: 'ladies-watch', code: '0012' },",
        "    'G-SHOCK': { section: 'watch_accessory', path: 'gshock', code: '0013' },",
        "    'ネックレス': { section: 'watch_accessory', path: 'necklace', code: '0020' },",
        "    'ブレスレット': { section: 'watch_accessory', path: 'bracelet', code: '0021' },",
        "    'リング': { section: 'watch_accessory', path: 'ring', code: '0022' },",
        "    '指輪': { section: 'watch_accessory', path: 'ring', code: '0022' },",
        "    'ピアス': { section: 'watch_accessory', path: 'piercing', code: '0023' },",
        "    'イヤリング': { section: 'watch_accessory', path: 'earring', code: '0024' },",
        "    'ゴルフクラブ': { section: 'sports', path: 'golf-club', code: '0010' },",
        "    'ゴルフ': { section: 'sports', path: 'golf', code: '0010' },",
        "    'ゴルフバッグ': { section: 'sports', path: 'golf-bag', code: '0011' },",
        "    'ゴルフシューズ': { section: 'sports', path: 'golf-shoes', code: '0012' },",
        "    'テニスラケット': { section: 'sports', path: 'tennis-racket', code: '0020' },",
        "    'テニス': { section: 'sports', path: 'tennis', code: '0020' },",
        "    '野球': { section: 'sports', path: 'baseball', code: '0030' },",
        "    'グローブ': { section: 'sports', path: 'baseball-glove', code: '0031' },",
        "    'バット': { section: 'sports', path: 'baseball-bat', code: '0032' },",
        "    'サッカー': { section: 'sports', path: 'soccer', code: '0040' },",
        "    'サッカーボール': { section: 'sports', path: 'soccer-ball', code: '0041' },",
        "    'サッカースパイク': { section: 'sports', path: 'soccer-spike', code: '0042' },",
        "    'バスケットボール': { section: 'sports', path: 'basketball', code: '0050' },",
        "    'バレーボール': { section: 'sports', path: 'volleyball', code: '0055' },",
        "    '水泳': { section: 'sports', path: 'swimming', code: '0060' },",
        "    '水着': { section: 'sports', path: 'swimwear', code: '0061' },",
        "    'ゴーグル': { section: 'sports', path: 'goggles', code: '0062' },",
        "    'フィットネス': { section: 'sports', path: 'fitness', code: '0070' },",
        "    'トレーニング': { section: 'sports', path: 'training', code: '0071' },",
        "    'ダンベル': { section: 'sports', path: 'dumbbell', code: '0072' },",
        "    'ヨガマット': { section: 'sports', path: 'yoga-mat', code: '0073' },",
        "    'プロテイン': { section: 'sports', path: 'protein', code: '0074' },",
        "    'スキー': { section: 'sports', path: 'ski', code: '0080' },",
        "    'スノーボード': { section: 'sports', path: 'snowboard', code: '0081' },",
        "    'ウェア': { section: 'sports', path: 'sports-wear', code: '0090' },",
        "    'テント': { section: 'outdoor', path: 'tent', code: '0010' },",
        "    'タープ': { section: 'outdoor', path: 'tarp', code: '0011' },",
        "    'シュラフ': { section: 'outdoor', path: 'sleeping-bag', code: '0020' },",
        "    '寝袋': { section: 'outdoor', path: 'sleeping-bag', code: '0020' },",
        "    'キャンプ': { section: 'outdoor', path: 'camp', code: '0001' },",
        "    'キャンプ用品': { section: 'outdoor', path: 'camp', code: '0001' },",
        "    'アウトドアチェア': { section: 'outdoor', path: 'outdoor-chair', code: '0030' },",
        "    'アウトドアテーブル': { section: 'outdoor', path: 'outdoor-table', code: '0031' },",
        "    'クーラーボックス': { section: 'outdoor', path: 'cooler-box', code: '0040' },",
        "    'ランタン': { section: 'outdoor', path: 'lantern', code: '0050' }",
        "};"
    ];
    lines.splice(start, end - start + 1, ...cleanMap);
    console.log("Fixed market_research.js KAKAKU_CATEGORY_MAP");
}
fs.writeFileSync('scripts/lib/market_research.js', lines.join('\n'));
