const { exiftool } = require('exiftool-vendored');
const path = require('path');
const fs = require('fs');

/**
 * Injects Google-compliant AI metadata into an image.
 * Uses IPTC DigitalSourceType: TrainedAlgorithmicMedia
 * 
 * @param {string} filePath - Absolute path to the image file
 * @returns {Promise<boolean>} - True if successful
 */
async function injectAiMetadata(filePath) {
    if (!fs.existsSync(filePath)) {
        console.error(`[Metadata] File not found: ${filePath}`);
        return false;
    }

    try {
        console.log(`[Metadata] Injecting IPTC tags into: ${path.basename(filePath)}`);

        // standard tag for AI media
        // http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia
        await exiftool.write(filePath, {
            'IPTC:DigitalSourceType': 'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia',
            'XMP-iptcCore:DigitalSourceType': 'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia',
            'Make': 'ChoiceGuide AI Engine',
            'Model': 'gemini-3.1-pro-preview',
            'Copyright': 'Copyright 2026 ChoiceGuide. All rights reserved.',
            'UserComment': 'Generated by AI for ChoiceGuide Review System.'
        });

        // Exiftool creates a backup file (empty extension or _original). Delete it.
        const backupPath = filePath + '_original';
        if (fs.existsSync(backupPath)) {
            fs.unlinkSync(backupPath);
        }

        console.log(`[Metadata] Success: AI tags added.`);
        return true;
    } catch (error) {
        console.error(`[Metadata] Failed to write tags:`, error);
        return false;
    }
}

/**
 * Cleanup function to close the exiftool process.
 * Should be called when the script finishes.
 */
async function closeExifTool() {
    await exiftool.end();
}

module.exports = { injectAiMetadata, closeExifTool };
