const fs = require('fs');
const path = require('path');

// Configuration
const PRODUCTS_FILE = path.join(__dirname, '../src/data/products.json');
const OUTPUT_DIR = path.join(__dirname, '../out/link');
const PHP_FILE = path.join(OUTPUT_DIR, 'index.php');
const HTACCESS_FILE = path.join(OUTPUT_DIR, '.htaccess');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// 1. Read Product Data
try {
    const rawData = fs.readFileSync(PRODUCTS_FILE, 'utf8');
    const products = JSON.parse(rawData);

    // 2. Generate Redirect Map
    const redirectMap = {};
    products.forEach(product => {
        if (product.id && product.affiliateLinks && product.affiliateLinks.amazon) {
            redirectMap[product.id] = product.affiliateLinks.amazon;
        }
    });

    // 3. Generate PHP File
    const phpContentRobust = `<?php
// Auto-generated by scripts/generate_redirects.js
// Do not edit manually

// Prevent indexing of this redirect endpoint
header("X-Robots-Tag: noindex, nofollow");

$map_json = '${JSON.stringify(redirectMap).replace(/'/g, "\\'")}';
$redirects = json_decode($map_json, true);

$id = $_GET['id'] ?? '';

if (isset($redirects[$id])) {
    // 302 Found (Temporary Redirect) - Recommended for affiliate links to prevent caching issues with tracking
    header("Location: " . $redirects[$id], true, 302);
    exit;
}

// Fallback: Check for URL-encoded ID or partial matches if needed (optional)
// For now, strict match.

header("HTTP/1.0 404 Not Found");
?>
<!DOCTYPE html>
<html>
<head><title>Link Not Found</title></head>
<body>
    <h1>Product link not found</h1>
    <p>The requested product link could not be found. Please return to the <a href="/">home page</a>.</p>
</body>
</html>
`;

    fs.writeFileSync(PHP_FILE, phpContentRobust);
    console.log(`Generated ${PHP_FILE} with ${Object.keys(redirectMap).length} redirects.`);


    // 4. Generate .htaccess File
    // This rewrites /link/product-id to /link/index.php?id=product-id
    const htaccessContent = `
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /link/
    
    # If the request is not a file or directory
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    
    # Rewrite everything else to index.php?id=...
    RewriteRule ^(.*)$ index.php?id=$1 [L,QSA]
</IfModule>
`;
    // Note: 'RewriteBase /link/' assumes the script is in /link/ subfolder relative to docroot.
    // If output: 'export' puts it in /link/, then on accessing https://site.com/link/foo
    // The .htaccess in /link/ takes effect.

    fs.writeFileSync(HTACCESS_FILE, htaccessContent.trim());
    console.log(`Generated ${HTACCESS_FILE}`);

} catch (error) {
    console.error('Error generating redirects:', error);
    process.exit(1);
}
